services:
  - type: web
    name: sub-recorder
    runtime: image
    image:
      url: docker.io/shenghuo2/sub-recorder:latest
    plan: free
    envVars:
      - key: DATABASE_PATH
        value: /app/data/subscriptions.db
      - key: PORT
        value: "3000"
      - key: INIT_USERNAME
        sync: false
      - key: INIT_PASSWORD
        sync: false
      - key: DEMO_MODE
        sync: false
